version: "3.8"

services:
  postgres:
    container_name: re_learn_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-re-learn}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-re-learn}
      PGDATA: /data/postgres
      POSTGRES_DB: re-learn
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: re_learn_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
